# Esta línea le dice a AWS qué versión del formato de plantilla estás usando.
AWSTemplateFormatVersion: '2010-09-09'

# Esta línea activa las macros de SAM para simplificar la sintaxis (ej. AWS::Serverless::Function).
Transform: AWS::Serverless-2016-10-31

Description: >
  Microservicio para la gestión de órdenes, implementado con Spring Boot en AWS Lambda.

# ====================================================================
# === ESTA ES LA SECCIÓN OBLIGATORIA QUE ESTÁ CAUSANDO EL ERROR ===
# Asegúrate de que "Resources:" no tenga NINGÚN espacio al principio.
# ====================================================================
Resources:
  # Definición de tu Función Lambda
  OrdenesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Handler: pillihuaman.com.pe.examen.StreamLambdaHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          ORDENES_TABLE_NAME: !Ref OrdenesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdenesTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # Definición de tu Tabla DynamoDB
  OrdenesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ordenId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

# (Opcional pero recomendado) Esta sección define las salidas, como la URL de tu API
Outputs:
  OrdenesApiEndpoint:
    Description: "URL del endpoint de API Gateway"
    Value: !Sub "https://{ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orden"